//
//  ServerConstants.m
//  Qlink
//
//  Created by Jelly Foo on 2019/8/20.
//  Copyright © 2019 pan. All rights reserved.
//

#import "ServerConstants.h"

@implementation ServerConstants

NSString *const Server_Data = @"data";
NSString *const Server_Msg = @"msg";
NSString *const Server_Code = @"code";
NSString *const Server_Result = @"result";
NSInteger const Server_Code_Success = 0;
NSInteger const Server_TimeOut_Code = -1001;
NSInteger const Server_ConnectLost_Code = -1005;
NSInteger const Server_CouldNotConnectServer_Code = -1004;


NSString *const ssIdsave_Url = @"/api/neo/ssId/save.json"; // 1、    保存ssid
NSString *const recordsave_Url = @"/api/neo/record/save.json"; // 2、保存record 接口
NSString *const ssIdquery_Url = @"/api/neo/ssId/query.json"; // 3、查询单个ssid 接口
NSString *const recordquery_Url = @"/api/neo/record/query.json"; // 4、查询单个record接口
NSString *const ssIdquerys_Url = @"/api/neo/ssId/querys.json"; // 5、查询多个ssid 接口
NSString *const recordquerys_Url = @"/api/neo/record/querys.json"; // 6、查询多个record接口
NSString *const createWallet_Url = @"/api/neo/createWallet.json"; // 7、创建钱包
NSString *const createWalletV2_Url = @"/api/neo/createWalletV2.json";
//NSString *const getTokenBalance_Url = @"/api/neo/getTokenBalance.json"; // 8、获取资产balance
NSString *const transfer_Url = @"/api/neo/transfer.json"; // 9、交易接口
NSString *const wifds_Url = @"/api/neo/wif/ds.json"; // 10、wifi打赏接口
NSString *const exportKey_Url = @"/api/neo/exportKey.json"; // 11、导入钱包接口
NSString *const getTokenInfo_Url = @"/api/neo/getTokenInfo.json"; // 12、获取tokenInfo信息接口
NSString *const getTranRecord_Url = @"/api/neo/getTranRecord.json"; // 13、获取交易记录接口
NSString *const recordsaveOver_Url = @"/api/neo/record/saveOver.json"; // 14、断开wifi时，保存record 接口
NSString *const raw_Url = @"/api/neo/raw.json"; // 15、获取汇率接口
NSString *const neoExchangeQlc_Url = @"/api/neo/neoExchangeQlc.json"; // 16、neo兑换qlc接口
NSString *const neoExchangeQlcV2_Url = @"/api/neo/neoExchangeQlcV2.json"; // 16、neo兑换qlc接口2
NSString *const ssIdrecoveryAssets_Url = @"/api/neo/ssId/recoveryAssets.json"; // 17、根据地址恢复资产接口
NSString *const recordrecoveryRecords_Url = @"/api/neo/record/recoveryRecords.json"; // 18、根据地址恢复记录接口
NSString *const vpnsave_Url = @"/api/neo/vpn/save.json"; // 19、注册vpn资产接口
NSString *const vpnquery_Url = @"/api/neo/vpn/query.json"; // 20、根据国家获取vpn资产列表接口
NSString *const vpnsaveCVpnRecord_Url = @"/api/neo/vpn/saveCVpnRecord.json"; // 21、保存VPN记录接口
NSString *const validateAssetIsexist_Url = @"/api/neo/validateAssetIsexist.json"; // 22、验证资产是否存在接口
NSString *const ssIdregisterWifiByFee_Url = @"/api/neo/ssId/registerWifiByFee.json"; // 23、注册wifi资产（包含扣费功能）接口
NSString *const ssIdregisterVpnByFee_Url = @"/api/neo/ssId/registerVpnByFee.json"; // 24、注册vpn资产（包含扣费功能）接口
NSString *const ssIdregisterWifiByFeeV2_Url = @"/api/neo/ssId/registerWifiByFeeV2.json"; // 25、注册wifi资产接口（第二版本）
NSString *const ssIdregisterVpnByFeeV2_Url = @"/api/neo/ssId/registerVpnByFeeV2.json"; // 26、注册vpn资产接口(第二版本)
NSString *const batchExportKey_Url = @"/api/neo/batchExportKey.json"; // 27、批量导入钱包
NSString *const uploadHeadView_Url = @"/fapi/user/uploadHeadView.json"; // 28、上传用户头像
NSString *const getHeadView_Url = @"/fapi/user/getHeadView.json"; // 29、获取用户头像
NSString *const heartbeat_Url = @"/api/neo/heartbeat.json"; // 30 资产心跳接口
NSString *const ssIdregisterWifiByFeeV3_Url = @"/api/neo/ssId/registerWifiByFeeV3.json"; // 31、注册wifi资产接口（第三版本）
NSString *const ssIdregisterVpnByFeeV3_Url = @"/api/neo/ssId/registerVpnByFeeV3.json"; // 32、注册vpn资产接口(第三版本)
NSString *const ssIdregisterVpnByFeeV4_Url = @"/api/neo/ssId/registerVpnByFeeV4.json"; // 44、注册vpn资产接口(第四版本)

NSString *const ssIdupdateWifiInfoV3_Url = @"/api/neo/ssId/updateWifiInfoV3.json"; // 33、更新wifi基本信息接口
NSString *const ssIdupdateVpnInfoV3_Url = @"/api/neo/ssId/updateVpnInfoV3.json"; // 34、更新vpn基本信息接口
NSString *const queryVpnV2_Url = @"/api/neo/vpn/queryVpnV2.json"; // 35、根据国家获取vpn资产列表接口（第二版）
NSString *const heartbeatV2_Url = @"/api/neo/heartbeatV2.json"; // 36 资产心跳接口（第二版）
NSString *const unpspentAsset_Url = @"/api/neo/unpspentAsset.json"; // 37获取未花费的交易输出
NSString *const allUnpspentAsset_Url = @"/api/neo/allUnpspentAsset.json"; // 38 获取所有未花费的交易输出
NSString *const sendrawtransaction_Url = @"/api/neo/sendrawtransaction.json"; // 39 交易广播
NSString *const heartbeatV3_Url = @"/api/neo/heartbeatV3.json"; // 40 资产心跳接口（第三版）
//NSString *const mainAddress_Url  = @"/api/neo/getMainAddress.json"; //47 获取主帐号地址 (第一版)
NSString *const mainAddressV2_Url  = @"/api/neo/getMainAddressV2.json"; //49 获取主帐号地址 (第f二版)
NSString *const transTypeOperate_Url  = @"/api/neo/ssId/transTypeOperate.json"; // vpn wifi打赏
NSString *const getServerTime_Url = @"/api/wc/getServerTime.json"; // 51、获取服务器时间接口
NSString *const queryVpnV3_Url = @"/api/neo/vpn/queryVpnV3.json"; // 55、根据国家获取vpn资产列表接口（第三版）
NSString *const zsFreeNum_Url  = @"/api/neo/zsFreeNum.json"; //56、赠送免费次数接口
NSString *const freeConnection_Url  = @"/api/neo/vpn/freeConnection.json"; //57、免费连接vpn接口
NSString *const queryFreeRecords_Url  = @"/api/neo/queryFreeRecords.json";  //58、查找免费使用记录接口
NSString *const reportVpnInfo_Url = @"/api/neo/reportVpnInfo.json";  // 46、上报vpn信息接口
NSString *const queryActs_Url  = @"/api/act/queryActs.json";  // 59、获取活动列表接口
NSString *const queryVpnRankings_Url  = @"/api/act/queryVpnRankings.json"; // 60、获取活动vpn列表
NSString *const isShowRanking_Url  = @"/api/act/isShowRanking.json"; // 61、活动ranking控制开关接
NSString *const ssIdRegisterVpnByFeeV5_Url = @"/api/neo/ssId/registerVpnByFeeV5.json"; // 62、注册vpn资产接口(第五版本)
NSString *const ssIdUpdateVpnInfoV4_Url = @"/api/neo/ssId/updateVpnInfoV4.json"; // 63、更新vpn基本信息接口(第四版本)
NSString *const ssIdRegisterVpnByFeeV6_Url = @"/api/neo/ssId/registerVpnByFeeV6.json"; // 64、注册vpn资产接口(第六版本)
NSString *const ethAddressInfo_Url = @"/api/eth/address_info.json"; // 65、获取ETH地址的信息(包含token余额)
NSString *const neoAddressInfo_Url = @"/api/neo/address_info.json"; // 66、获取NEO地址的信息(包含token余额)
NSString *const binaKlines_Url = @"/api/bina/klines.json"; // 67获取token K线图数据
NSString *const binaTpcs_Url = @"/api/bina/tpcs.json"; // 68获取token 24小时涨跌信息
NSString *const ethAddressHistory_Url = @"/api/eth/address_history.json"; // 69获取地址的交易历史
NSString *const neoGetAllTransferByAddress_Url = @"/api/neo/getAllTransferByAddress.json"; // 70 NEO根据地址获取所有的交易记录
NSString *const tokenPrice_Url = @"/api/token/price.json"; // 71 获取数字货币的价格
NSString *const walletReport_wallet_create_Url = @"/api/wallet/report_wallet_create.json"; // 72 上报创建钱包地址接口
NSString *const walletReport_wallet_transfer_Url = @"/api/wallet/report_wallet_transfer.json"; // 73 上报钱包转账接口
NSString *const neoMainNetNep5Transfer_Url = @"/api/neo/mainNet/nep5Transfer.json"; // 74 NEO所有代币正式转账接口
NSString *const neoMainNetAllUnpspentAsset_Url = @"/api/neo/mainNet/allUnpspentAsset.json"; // 75 获取正式链未花费的接口
NSString *const ethAddress_transactions_Url = @"/api/eth/address_transactions.json"; // 76 获取地址的交易历史(ETH)
NSString *const neoGotWGas_Url = @"/api/neo/gotWGas.json"; // 77 领取winGas接口
NSString *const neoQueryWGas_Url = @"/api/neo/queryWGas.json"; // 78 查询winGas接口
NSString *const neoGetClaims_Url = @"/api/neo/getClaims.json"; // 79 查询claimGas接口
NSString *const eosNew_account_Url = @"/api/eos/new_account.json"; // 80 创建EOS账户
NSString *const eosGet_token_list_Url = @"/api/eos/get_token_list.json"; // 81 查询账户的某个代币或所有代币余额
NSString *const eosGet_account_related_trx_info_Url = @"/api/eos/get_account_related_trx_info.json"; // 82 查询账户的代币转账记录
NSString *const eosGet_account_resource_info_Url = @"/api/eos/get_account_resource_info.json"; // 83 查询账户的RAM/CPU/NET等资源信息
NSString *const eosGet_account_info_Url = @"/api/eos/get_account_info.json"; // 84 查询账户的基本信息
NSString *const binaGetTokens_Url = @"/api/bina/getTokens.json"; // 85 查询支持24小时涨跌的所有tokens
NSString *const eosEos_verify_Url = @"/api/eos/eos_verify.json"; // 86 EOS数据签名公匙验证
NSString *const walletReport_wallet_create_v2_Url = @"/api/wallet/report_wallet_create_v2.json"; // 87 上报创建钱包地址接口（第二版本）
NSString *const ethEth_address_Url = @"/api/eth/eth_address.json"; // 88 系统ETH地址
NSString *const ethEth_for_activate_eos_wallet = @"/api/eth/eth_for_activate_eos_wallet.json"; // 89 激活EOS钱包所需ETH数量
NSString *const eosEos_resource_price_Url = @"/api/eos/eos_resource_price.json"; // 90 获取资源[RAM,CPU,NET]价格
NSString *const btcRawaddr_Url = @"/api/btc/rawaddr.json"; // 91 BTC查询地址交易记录
NSString *const wgas_history_Url = @"/api/neo/wgas_history.json"; // 92 资产[VPN]获取WGAS记录
NSString *const convert_wgas_Url = @"/api/neo/convert_wgas.json"; // 93 兑换WGAS
NSString *const signup_code_Url = @"/api/vcode/signup_code.json"; // 94 获取注册验证码
NSString *const sign_up_Url = @"/api/user/sign_up.json"; // 95 注册
NSString *const sign_in_Url = @"/api/user/sign_in.json"; // 96 登录
NSString *const invite_Url = @"/api/user/invite.json"; // 97 邀请好友
NSString *const invite_rankings_Url = @"/api/user/invite_rankings.json"; // 98 邀请排名
NSString *const rich_list_Url = @"/api/user/rich_list.json"; // 99 富豪榜
NSString *const product_list_Url = @"/api/financial/product_list.json"; // 100 产品列表
NSString *const product_info_Url = @"/api/financial/product_info.json"; // 101 产品详情
NSString *const order_Url = @"/api/financial/order.json"; // 102 购买产品
NSString *const order_list_Url = @"/api/financial/order_list.json"; // 103 订单列表
NSString *const redeem_Url = @"/api/financial/redeem.json"; // 104 订单赎回
NSString *const vcode_signin_code_Url = @"/api/vcode/signin_code.json"; // 105 获取登录验证码
NSString *const user_signin_code_Url = @"/api/user/signin_code.json"; // 106 验证码登录
NSString *const vcode_change_password_code_Url = @"/api/vcode/change_password_code.json"; // 107 获取修改密码验证码
NSString *const vcode_change_phone_code_Url = @"/api/vcode/change_phone_code.json"; // 108 获取更换手机验证码
NSString *const vcode_change_email_code_Url = @"/api/vcode/change_email_code.json"; // 109 获取更换邮箱验证码
NSString *const user_change_password_Url = @"/api/user/change_password.json"; // 110 修改密码
NSString *const user_change_phone_Url = @"/api/user/change_phone.json"; // 111 更换手机号码
NSString *const user_change_email_Url = @"/api/user/change_email.json"; // 112 更换邮箱
NSString *const user_change_nickname_Url = @"/api/user/change_nickname.json"; // 113 修改昵称
NSString *const user_upload_headview_Url = @"/fapi/user/upload_headview.json"; // 114、上传用户头像（不需要sign验证）
NSString *const history_record_Url = @"/api/financial/history_record.json"; // 115 财富-历史记录
NSString *const upload_id_card_Url = @"/fapi/user/upload_id_card.json"; // 116、上传用户身份证/护照
NSString *const entrust_order_Url = @"/api/entrust/order.json"; // 117 添加委托订单
NSString *const entrust_order_list_Url = @"/api/entrust/order_list.json"; // 118 委托订单列表
NSString *const entrust_order_info_Url = @"/api/entrust/order_info.json"; // 119 委托订单详情
NSString *const entrust_cancel_order_Url = @"/api/entrust/cancel_order.json"; // 120 取消委托订单
NSString *const trade_buy_order_Url = @"/api/trade/buy_order.json"; // 121 生成买单
NSString *const trade_buyer_confirm_Url = @"/api/trade/buyer_confirm.json"; // 122 买家确认已转出USDT
NSString *const trade_sell_order_Url = @"/api/trade/sell_order.json"; // 123 生成卖单
NSString *const trade_sell_order_v2_Url = @"/api/trade/sell_order_v2.json"; // 生成卖单  v2
NSString *const trade_seller_confirm_Url = @"/api/trade/seller_confirm.json"; // 124 卖家确认已收到USDT
NSString *const trade_order_list_Url = @"/api/trade/order_list.json"; // 125 买卖订单列表
NSString *const trade_order_info_Url = @"/api/trade/order_info.json"; // 126 委托订单详情
//NSString *const trade_appeal_Url = @"/api/trade/appeal.json"; // 127 申诉
NSString *const trade_appeal_Url = @"/fapi/user/appeal.json"; // 127 申诉
NSString *const user_user_info_Url = @"/api/user/user_info.json"; // 128 用户详情
NSString *const trade_cancel_Url = @"/api/trade/cancel.json"; // 129 买卖订单取消
NSString *const sys_version_info_Url = @"/api/sys/version_info.json"; // 130  APP版本信息
NSString *const pairs_pairs_Url = @"/api/pairs/pairs.json"; // 交易对
NSString *const sys_contract_unlock_Url = @"/api/sys/contract_unlock.json"; // 调用智能合约'unlock'方法
NSString *const topup_product_list_Url = @"/api/topup/product_list.json"; // 132 充值产品列表
NSString *const topup_order_Url = @"/api/topup/order.json"; // 133 充值订单
NSString *const topup_order_list_Url = @"/api/topup/order_list.json"; // 134 充值订单列表
NSString *const topup_cancel_order_Url =@"/api/topup/cancel_order.json"; // 135 取消订单
NSString *const log_save_Url = @"/api/log/save.json"; // 136 保存错误日志
NSString *const user_bind_Url = @"/api/user/bind.json"; // 137 用户绑定QLC-CHAIN钱包地址
NSString *const reward_reward_list_Url = @"/api/reward/reward_list.json"; // 138 QGAS奖励列表
NSString *const reward_claim_bind_Url = @"/api/reward/claim_bind.json"; // 139 领取绑定钱包获取的QGAS奖励
NSString *const reward_reward_total_Url = @"/api/reward/reward_total.json"; // 140 QGAS奖励总数
NSString *const sys_dict_Url = @"/api/sys/dict.json"; // 141 字典查询
NSString *const user_invite_amount_Url = @"/api/user/invite_amount.json"; // 142 邀请人数
NSString *const reward_claim_invite_Url = @"/api/reward/claim_invite.json"; // 143 领取邀请用户获取的QGAS奖励
NSString *const user_bind_jpush_Url = @"/api/user/bind_jpush.json"; // 144 用户绑定极光推送ID
NSString *const user_logout_Url = @"/api/user/logout.json"; // 145 退出登录
NSString *const topup_pay_token_Url = @"/api/topup/pay_token.json"; // 
NSString *const topup_order_confirm_Url = @"/api/topup/order_confirm.json"; // 147 充值支付币确认
NSString *const trade_mining_list_Url = @"/api/trade_mining/list.json"; // 148 交易挖矿活动列表
NSString *const trade_mining_reward_list_Url = @"/api/trade_mining/reward_list.json"; // 149 交易挖矿奖励列表
NSString *const trade_mining_claim_Url = @"/api/trade_mining/claim.json"; // 150 领取交易挖矿奖励
NSString *const trade_mining_reward_total_Url = @"/api/trade_mining/reward_total.json"; // 151 交易挖矿奖励总数
NSString *const trade_mining_reward_rankings_Url = @"/api/trade_mining/reward_rankings.json"; // 152 交易挖矿奖励排行榜
NSString *const trade_mining_index_Url = @"/api/trade_mining/index.json"; //
NSString *const user_red_point_Url = @"/api/user/red_point.json"; // 红点
NSString *const sys_txid_backup_Url = @"/api/sys/txid_backup.json"; //
NSString *const trade_sell_order_txid_Url = @"/api/trade/sell_order_txid.json"; // 156 卖单保存买卖币TXID
NSString *const topup_country_list_Url = @"/api/topup/country_list.json"; // 158 国家列表
NSString *const topup_product_list_v2_Url = @"/api/topup/product_list_v2.json"; // 159 充值产品列表V2
NSString *const topup_isp_list_Url = @"/api/topup/isp_list.json"; // 160 运营商列表
NSString *const topup_province_list_Url = @"/api/topup/province_list.json"; // 161 省/区域列表
NSString *const topup_order_v2_Url = @"/api/topup/order_v2.json"; // 162 充值订单V2
NSString *const topup_deduction_token_txid_Url = @"/api/topup/deduction_token_txid.json"; // 163 保存充值订单的抵扣币转入TXID
NSString *const topup_pay_token_txid_Url = @"api/topup/pay_token_txid.json"; // 164 保存充值订单的支付币转入TXID
NSString *const user_bind_qlc_address_Url = @"/api/user/bind_qlc_address.json"; // 165 用户绑定QLC-CHAIN钱包地址
NSString *const user_topup_reward_rankings_Url = @"/api/user/topup_reward_rankings.json"; // 166 充值奖励列表
NSString *const topup_group_kind_list_Url = @"/api/topup/group_kind_list.json"; // 167 团购类型列表
NSString *const topup_create_group_Url = @"/api/topup/create_group.json"; // 168 创建团购
NSString *const topup_group_list_Url = @"/api/topup/group_list.json"; // 169 团购列表
NSString *const topup_join_group_Url = @"/api/topup/join_group.json"; // 170 参加团购
NSString *const topup_group_item_list_Url = @"/api/topup/group_item_list.json"; // 171 团购条目列表
NSString *const topup_item_deduction_token_txid_Url = @"/api/topup/item_deduction_token_txid.json"; // 172 团购条目抵扣币TXID
NSString *const topup_item_deduction_token_confirm_Url = @"/api/topup/item_deduction_token_confirm.json"; // 173 团购条目抵扣币确认
NSString *const topup_item_pay_token_txid_Url = @"/api/topup/item_pay_token_txid.json"; // 174 团购条目支付币TXID
NSString *const user_invite_list_Url = @"/api/user/invitee_list.json"; // 175 受邀者列表
NSString *const topup_dedicate_list_Url = @"/api/topup/dedicate_list.json"; // 176 充值奖励贡献者列表
NSString *const topup_product_list_v3_Url = @"/api/topup/product_list_v3.json"; // 177 充值产品列表V3
NSString *const sys_vote_Url = @"/api/sys/vote.json"; // 180 QGAS销毁投票
NSString *const sys_vote_result_Url = @"/api/sys/vote_result.json"; // 181 QGAS销毁投票结果
NSString *const burn_qgas_list_Url = @"/api/burn_qgas/list.json"; // 
NSString *const burn_qgas_list_v2_Url = @"/api/burn_qgas/list_v2.json";
NSString *const vcode_verify_code_Url = @"/api/vcode/verify_code.json"; // 182 获取验证码
NSString *const reward_claim_invite_v2_Url = @"/api/reward/claim_invite_v2.json"; // 183 领取邀请用户获取的QGAS奖励V2
NSString *const reward_claim_bind_v2_Url = @"/api/reward/claim_bind_v2.json"; // 184 领取绑定钱包获取的QGAS奖励V2
NSString *const sys_index_Url = @"/api/sys/index.json"; //
NSString *const sys_location_Url = @"/api/sys/location.json"; // 
NSString *const defi_project_list_Url = @"/api/defi/project_list.json"; // 190 DeFi项目列表
NSString *const defi_stats_list_Url = @"/api/defi/stats_list.json"; // 191 DeFi项目统计数据列表
NSString *const defi_rating_Url = @"/api/defi/rating.json"; // 192 DeFi项目评级
NSString *const defi_category_list_Url = @"/api/defi/category_list.json"; // 193 DeFi项目类型列表
NSString *const defi_project_Url = @"/api/defi/project.json"; // 194 DeFi项目详情
NSString *const defi_news_list_Url = @"/api/defi/news_list.json"; // 195 DeFi新闻列表
NSString *const defi_news_Url = @"/api/defi/news.json"; // 196 DeFi 新闻详情
NSString *const defi_rating_info_Url = @"/api/defi/rating_info.json"; // 197 DeFi 项目评级详情
NSString *const defi_stats_cache_Url = @"/api/defi/stats_cache.json"; // 198 DeFi 项目统计缓存


NSString *const allUnpspentAsset_url = @"/api/neo/mainNet/allUnpspentAsset.json"; // 正式接口（neo及其token转账）
NSString *const allUnpspentAsset_v2_url = @"/api/neo/mainNet/allUnpspentAsset_v2.json"; // 正式接口（neo及其token转账）

@end
